# Generated by Django 3.0.8 on 2020-08-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='use_form',
            new_name='use_from',
        ),
    ]
